name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/humble-image-pc:latest
  
jobs:

  build_and_push:
    name: Build image & push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
    
      - name: Checkout repository  
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Image
        run: |
          cd humble  
          bash build-image-local.sh
          
      - name : Push Image
        run: |
          docker tag humble-image-pc ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker image ls
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
