name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/humble-image-pc:latest
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository  
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Image
        run:  bash build-image-local.sh
          
      - name : Push Image
        run: |
          docker tag humble-image-pc ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker image ls
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}